'use client';
import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, CloudRain, FileSearch, History, Image as ImageIcon, Loader2, ShieldCheck, Upload, Waves } from 'lucide-react';
import { apiFileUrl, createInspection, getEvidence, getPredictions, getSites, Evidence, Inspection, Prediction, Site } from '../lib/api';
const evidenceColors: Record<string, string> = { documented: 'text-sentinel-green bg-sentinel-green/10 border-sentinel-green/20', 'ai-inferred': 'text-sentinel-blue bg-sentinel-blue/10 border-sentinel-blue/20', projected: 'text-sentinel-orange bg-sentinel-orange/10 border-sentinel-orange/20', uncertain: 'text-zinc-300 bg-white/5 border-white/10' };
function Badge({ children, tone = 'ai-inferred' }: { children: React.ReactNode; tone?: string }) { return <span className={`inline-flex items-center rounded-full border px-2 py-1 text-[9px] font-mono uppercase tracking-widest ${evidenceColors[tone] || evidenceColors.uncertain}`}>{children}</span>; }
export default function InspectionWorkbench() {
  const [sites, setSites] = useState<Site[]>([]), [siteId, setSiteId] = useState<number | undefined>(), [file, setFile] = useState<File | null>(null), [preview, setPreview] = useState<string | null>(null), [hint, setHint] = useState(''), [inspection, setInspection] = useState<Inspection | null>(null), [predictions, setPredictions] = useState<Prediction[]>([]), [evidence, setEvidence] = useState<Evidence[]>([]), [loading, setLoading] = useState(false), [error, setError] = useState(''), [activeHorizon, setActiveHorizon] = useState(200);
  useEffect(() => { getSites().then(setSites).catch(() => setError('Backend is not reachable. Start FastAPI and set NEXT_PUBLIC_API_BASE_URL.')); }, []);
  const handleFile = (event: ChangeEvent<HTMLInputElement>) => { const next = event.target.files?.[0] || null; setFile(next); setInspection(null); setPredictions([]); setError(''); if (preview) URL.revokeObjectURL(preview); setPreview(next ? URL.createObjectURL(next) : null); };
  const runAnalysis = async () => { if (!file) return setError('Choose a monument image first.'); setLoading(true); setError(''); try { const result = await createInspection(file, siteId, hint); setInspection(result); const [p, e] = await Promise.all([getPredictions(result.id), result.site_id ? getEvidence(result.site_id) : Promise.resolve([])]); setPredictions(p); setEvidence(e); } catch (err) { setError(err instanceof Error ? err.message : 'Analysis failed.'); } finally { setLoading(false); } };
  const selectedSite = useMemo(() => sites.find(s => s.id === siteId), [sites, siteId]); void selectedSite;
  const selectedPredictions = predictions.filter(p => p.horizon_years === activeHorizon); const currentPrediction = selectedPredictions.find(p => p.scenario === 'Current conditions continue') || selectedPredictions[0]; const risk = inspection?.report?.risk_score ?? 0;
  return <section id="inspection" className="border-t border-white/5 bg-sentinel-charcoal py-24 px-6"><div className="mx-auto max-w-7xl space-y-10"><div className="max-w-3xl space-y-4"><span className="text-xs font-bold uppercase tracking-[0.3em] text-sentinel-gold">01 / EVIDENCE-AWARE INSPECTION</span><h2 className="font-serif text-4xl tracking-tight text-white md:text-6xl">Past. Present. Future.</h2><p className="max-w-2xl text-sm leading-relaxed text-zinc-400">Upload one ordinary monument photograph. Heritage Sentinels creates a traceable screening record, compares it with historical evidence, adds environmental context, scores preservation risk, and produces clearly labelled future scenarios.</p></div>
  <div className="grid gap-8 lg:grid-cols-12"><div className="space-y-5 lg:col-span-5"><div className="rounded-2xl border border-white/10 bg-black/30 p-5"><div className="mb-4 flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-zinc-500"><Upload size={13}/> Capture evidence</div><label className="group flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-white/10 bg-white/[0.02] p-6 text-center transition hover:border-sentinel-gold/60 hover:bg-sentinel-gold/[0.03]">{preview ? <img src={preview} alt="Selected monument" className="max-h-52 rounded-lg object-contain"/> : <><ImageIcon className="mb-3 text-sentinel-gold" size={34}/><span className="text-sm text-white">Choose JPG, PNG or WebP</span><span className="mt-2 text-[10px] text-zinc-600">Maximum 12 MB</span></>}<input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={handleFile}/></label></div>
    <div className="rounded-2xl border border-white/10 bg-black/30 p-5 space-y-4"><div><label className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-zinc-500">Known heritage site (optional)</label><select value={siteId ?? ''} onChange={e=>setSiteId(e.target.value ? Number(e.target.value) : undefined)} className="w-full rounded-lg border border-white/10 bg-black px-3 py-3 text-sm text-white outline-none focus:border-sentinel-gold"><option value="">Let the AI identify it</option>{sites.map(site=><option key={site.id} value={site.id}>{site.name} — {site.region}</option>)}</select></div><div><label className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-zinc-500">Site hint (optional)</label><input value={hint} onChange={e=>setHint(e.target.value)} placeholder="e.g. Konark Sun Temple" className="w-full rounded-lg border border-white/10 bg-black px-3 py-3 text-sm text-white placeholder:text-zinc-700 outline-none focus:border-sentinel-gold"/></div><button onClick={runAnalysis} disabled={loading || !file} className="flex w-full items-center justify-center gap-2 rounded-lg bg-sentinel-gold px-4 py-3 text-xs font-bold uppercase tracking-widest text-black transition hover:bg-white disabled:cursor-not-allowed disabled:opacity-40">{loading ? <><Loader2 className="animate-spin" size={14}/> Analyzing evidence...</> : <>Run Heritage Analysis <ArrowRight size={14}/></>}</button>{error && <div className="rounded-lg border border-sentinel-red/20 bg-sentinel-red/10 p-3 text-xs leading-relaxed text-red-200">{error}</div>}</div></div>
    <div className="lg:col-span-7">{!inspection ? <div className="flex h-full min-h-[520px] items-center justify-center rounded-2xl border border-white/5 bg-black/20 p-8 text-center"><div className="max-w-md space-y-4"><ShieldCheck className="mx-auto text-zinc-700" size={48}/><h3 className="font-serif text-3xl text-zinc-500">Your evidence report will appear here</h3><p className="text-xs leading-relaxed text-zinc-600">Documented evidence, AI inference, environmental context and future projections remain visibly separate.</p></div></div> : <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="SITE" value={inspection.site_identification || 'Unresolved'} detail={`${Math.round(inspection.site_confidence)}% confidence`} icon={<FileSearch size={14}/>}/><Metric label="PRESERVATION RISK" value={`${Math.round(risk)}/100`} detail={inspection.report.risk_band || 'SCREENING'} icon={<AlertTriangle size={14}/>}/><Metric label="ANALYSIS" value={inspection.analysis.provider === 'multimodal-vision' ? 'VISION AI' : 'LOCAL CV'} detail="Screening layer" icon={<Activity size={14}/>}/></div>
      <div className="grid gap-5 md:grid-cols-2"><Panel title="Present — uploaded evidence" icon={<ImageIcon size={13}/>}><div className="overflow-hidden rounded-xl border border-white/5 bg-black"><img src={preview || ''} alt="Uploaded monument evidence" className="max-h-80 w-full object-contain"/><div className="flex items-center justify-between border-t border-white/5 p-3"><Badge tone="documented">USER-UPLOADED EVIDENCE</Badge><span className="font-mono text-[10px] text-zinc-600">{inspection.original_filename}</span></div></div></Panel><Panel title="Present — AI condition screening" icon={<Activity size={13}/>}><div className="space-y-3">{Object.entries(inspection.analysis.observations || {}).map(([key,value])=><Bar key={key} label={key.replaceAll('_',' ')} value={Number(value)||0}/>)}</div><div className="mt-4 border-t border-white/5 pt-3 text-[10px] leading-relaxed text-zinc-600">AI-inferred visual flags are screening observations, not a structural diagnosis. Validate with a qualified conservator.</div></Panel></div>
      <Panel title="Historical memory" icon={<History size={13}/>}><div className="grid gap-3 md:grid-cols-4">{evidence.map(item=><div key={item.id} className="rounded-xl border border-white/5 bg-white/[0.02] p-4"><div className="font-mono text-lg text-sentinel-gold">{item.year}</div><div className="mt-2 text-xs font-medium text-white">{item.title}</div><Badge tone={item.source.toLowerCase().includes('prototype') ? 'uncertain' : (item.evidence_type.includes('archival') || item.evidence_type.includes('reference') ? 'documented' : 'ai-inferred')}>{item.source.toLowerCase().includes('prototype') ? 'UNVERIFIED PROTOTYPE' : item.evidence_type.replaceAll('-',' ')}</Badge><p className="mt-3 text-[10px] leading-relaxed text-zinc-600">{item.description}</p></div>)}</div><div className="mt-5 rounded-xl border border-dashed border-white/10 bg-white/[0.02] p-4 text-[10px] leading-relaxed text-zinc-500">{inspection.report.historical_visuals?.length ? inspection.report.historical_visuals.map(view=><div key={view.year}>{view.year}: {view.label}</div>) : 'No verified historical image is attached to this inspection. The system will not transform the current upload and present it as archival evidence.'}</div></Panel>
      <Panel title="Future scenarios" icon={<Waves size={13}/>}><div className="mb-5 flex gap-2">{[50,100,200].map(years=><button key={years} onClick={()=>setActiveHorizon(years)} className={`rounded-lg border px-3 py-2 text-[10px] font-bold uppercase tracking-widest ${activeHorizon===years?'border-sentinel-gold bg-sentinel-gold/10 text-sentinel-gold':'border-white/5 text-zinc-500'}`}>{years} years</button>)}</div>{currentPrediction ? <div className="grid gap-5 md:grid-cols-2"><div className="overflow-hidden rounded-xl border border-white/5 bg-black"><img src={apiFileUrl(currentPrediction.image_url) || ''} alt={`${activeHorizon}-year scenario`} className="h-72 w-full object-cover"/><div className="flex items-center justify-between border-t border-white/5 p-3"><Badge tone="projected">SIMULATED / PROJECTED</Badge><span className="font-mono text-xs text-sentinel-orange">{Math.round(currentPrediction.risk_score)}/100 risk</span></div></div><div className="space-y-4"><div className="text-xs leading-relaxed text-zinc-400">{currentPrediction.explanation}</div><div><div className="mb-2 text-[9px] font-bold uppercase tracking-widest text-zinc-600">Potential drivers</div><div className="flex flex-wrap gap-2">{currentPrediction.drivers.map(d=><span key={d} className="rounded-full border border-white/5 px-2 py-1 text-[9px] text-zinc-500">{d}</span>)}</div></div><div><div className="mb-2 text-[9px] font-bold uppercase tracking-widest text-zinc-600">Recommended actions</div><ul className="space-y-2 text-xs text-zinc-300">{currentPrediction.recommendations.slice(0,4).map(r=><li key={r} className="flex gap-2"><CheckCircle2 className="mt-0.5 shrink-0 text-sentinel-green" size={13}/>{r}</li>)}</ul></div></div></div> : <p className="text-xs text-zinc-500">No scenario generated.</p>}<div className="mt-5 grid gap-3 md:grid-cols-3">{selectedPredictions.map(p=><div key={p.id} className="rounded-xl border border-white/5 bg-white/[0.02] p-4"><div className="flex items-center justify-between"><span className="text-xs text-white">{p.scenario}</span><span className="font-mono text-xs text-sentinel-orange">{Math.round(p.risk_score)}</span></div><p className="mt-2 text-[10px] text-zinc-600">Confidence {Math.round(p.confidence*100)}%</p></div>)}</div></Panel>
    </div>}</div></div>
</div></section>;
}
function Metric({label,value,detail,icon}:{label:string;value:string;detail:string;icon:React.ReactNode}){return <div className="rounded-xl border border-white/5 bg-white/[0.02] p-4"><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-widest text-zinc-600">{icon}{label}</div><div className="mt-2 font-serif text-2xl text-white">{value}</div><div className="mt-1 text-[9px] uppercase tracking-widest text-zinc-600">{detail}</div></div>}
function Panel({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <div className="rounded-2xl border border-white/5 bg-white/[0.01] p-5"><div className="mb-4 flex items-center gap-2 text-[9px] font-bold uppercase tracking-widest text-zinc-500">{icon}{title}</div>{children}</div>}
function Bar({label,value}:{label:string;value:number}){const safe=Math.max(0,Math.min(100,value));return <div><div className="mb-1 flex justify-between text-[10px] text-zinc-500"><span className="capitalize">{label}</span><span className="font-mono text-zinc-300">{Math.round(safe)}%</span></div><div className="h-1 overflow-hidden rounded bg-zinc-900"><div className="h-full rounded bg-sentinel-gold transition-all" style={{width:`${safe}%`}}/></div></div>}
